### ISSUE TITLE
Menghapus Kode yang Tidak Perlu

### ISSUE THREAD

**Issue by jefrydco** [AdiPrimanto/Vue-cari-video-teks#1]
Hi Mas Adi, terima kasih telah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Adi.

Mas juga sudah menggunakan kerangka kerja CSS Bootstrap. Luar biasa Mas!

Namun saya ada 1 saran kecil Mas yakni menghapus kode yg tidak perlu. Pada berkas `index.html` baris 194-196 berikut:

https://github.com/AdiPrimanto/Vue-cari-video-teks/blob/28ed7f7cb3fb66b4c764ec3071495279db401878/index.html#L194-L196

Mas menambahkan perpustakaan JavaScript eksternal jQuery, Popper dan Bootstrap. Menurut saya Mas bisa menghapus kode tersebut karena Mas tidak menggunakan di halamannya Mas. Bahkan untuk Bootstrap pun Mas hanya menggunakan kerangka CSS nya saja.

Semangat Mas! 😄

**Comment by AdiPrimanto** [comment]
terimakasih banyak mas jefry atas masukannya.. issu nya sudah saya perbaiki
